import type { DentalStockManifest } from './dental-stock-types';

/** Generated by scripts/sync-pexels-dental-stock.ts; public rendering never calls Pexels. */
export const DENTAL_STOCK_MANIFEST = {
  "version": 1,
  "syncedAt": "2026-07-28T05:00:52.490Z",
  "assets": [
    {
      "assetId": "d9a1f019-4fde-5b47-adea-9701db114963",
      "stockKey": "stk.clinic.dental.implant.4269364",
      "origin": "licensed_stock",
      "providerAssetId": "4269364",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269364.webp",
      "alt": "A close-up of dental tools and a jaw model on a green background, ideal for dentistry themes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dental-tools-4269364/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "6327c8304f08757584d2a262fbbd413c280cd3308e39a1e2343264a306c4b77a"
      }
    },
    {
      "assetId": "9a435598-71e2-5487-bd62-73534fcac7d2",
      "stockKey": "stk.clinic.dental.implant.4269365",
      "origin": "licensed_stock",
      "providerAssetId": "4269365",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269365.webp",
      "alt": "Close-up image of dental tools and model teeth for professional dentistry setup.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dental-tools-4269365/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "6f08a7d49452984a2def35dea728a9990fc8aef667c307ee9fcd36174e86b642"
      }
    },
    {
      "assetId": "5d97e614-7e80-5a44-bd10-3d20bf5f995a",
      "stockKey": "stk.clinic.dental.implant.4269370",
      "origin": "licensed_stock",
      "providerAssetId": "4269370",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269370.webp",
      "alt": "Close-up of colorful dental tools and materials arranged on a green surface for dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dental-tools-4269370/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "6337853eb28b05543cfb7e4ea0b4525589ab10ab15f95d4c2b761df9556840c9"
      }
    },
    {
      "assetId": "1d03b744-7492-5858-8c54-57d37e9656d4",
      "stockKey": "stk.clinic.dental.implant.5355826",
      "origin": "licensed_stock",
      "providerAssetId": "5355826",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355826.webp",
      "alt": "A dental model and red protective glasses on a textured surface, highlighting dental health tools.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/close-up-photo-of-a-dental-cast-5355826/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "bc8f0658b25842480c962eb8ada245785702ded4b573c543f12711aab056a0b0"
      }
    },
    {
      "assetId": "af99bd8f-62d1-572d-a678-603450f2b85b",
      "stockKey": "stk.clinic.dental.implant.5355918",
      "origin": "licensed_stock",
      "providerAssetId": "5355918",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355918.webp",
      "alt": "Close-up of dental tools and safety glasses on a white tray, ready for use.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/dental-tools-on-a-white-surface-5355918/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "ca72aa1dc6cea68e79d822a66824169bc97d4382561f391b6c0ef39ebc99de65"
      }
    },
    {
      "assetId": "c89ec7c5-38d3-56e9-9da4-9c9b7cedba13",
      "stockKey": "stk.clinic.dental.implant.5355922",
      "origin": "licensed_stock",
      "providerAssetId": "5355922",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355922.webp",
      "alt": "Dental cast, shade guide, and safety glasses on a clinical tray for dental procedures.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/a-dental-cast-beside-a-shade-guide-5355922/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "1662cc23f4a63572d028c4fc30b0ed7f527bea83f7507b9214ca352ee9123a84"
      }
    },
    {
      "assetId": "1f1ca2a5-5ba9-50b8-b8b9-dc101220ff46",
      "stockKey": "stk.clinic.dental.implant.6502301",
      "origin": "licensed_stock",
      "providerAssetId": "6502301",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502301.webp",
      "alt": "Close-up of dental models displaying braces and dentures for orthodontic education.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dentures-6502301/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "aa08dc4666fb5f4ebcb1e102a3fbb016047c65a82d85a884c4b2294a8ff0b2bd"
      }
    },
    {
      "assetId": "aae29d58-a3b7-517a-9292-2df7e18dc272",
      "stockKey": "stk.clinic.dental.implant.6502339",
      "origin": "licensed_stock",
      "providerAssetId": "6502339",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502339.webp",
      "alt": "Three transparent dental models displayed on a white surface for educational purposes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dentures-6502339/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "46f174ceef9b920f302273a304d1689a9ec624eeddeb50279626e1c30af9cdc4"
      }
    },
    {
      "assetId": "511f4299-63c5-539a-abfd-dd804e70f540",
      "stockKey": "stk.clinic.dental.implant.6502343",
      "origin": "licensed_stock",
      "providerAssetId": "6502343",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502343.webp",
      "alt": "Close-up of a dental implant model featuring artificial teeth and jaw structure.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dental-implant-model-6502343/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "ca905c57236014f1a309ae77dbb406e400ab585f3ca674d4a23e6806a4c20754"
      }
    },
    {
      "assetId": "01da4537-e653-52af-a15b-1af39a5d790d",
      "stockKey": "stk.clinic.dental.implant.6528857",
      "origin": "licensed_stock",
      "providerAssetId": "6528857",
      "category": "implant",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6528857.webp",
      "alt": "A minimalist display of dental and skull models, ideal for medical or educational themes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/skulls-and-denture-cast-on-a-white-surface-6528857/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d1b8dac1dbe63a2e8b4b73548a01cada4ce085827ce16b1584014a2aa848ab6a"
      }
    },
    {
      "assetId": "ce7db2de-a5aa-595d-85fb-02f765c2084c",
      "stockKey": "stk.clinic.dental.orthodontic.6528865",
      "origin": "licensed_stock",
      "providerAssetId": "6528865",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6528865.webp",
      "alt": "Close-up view of colorful orthodontic elastics arranged in a dental equipment box.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-photo-of-dental-elastics-6528865/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "c1b02a790faf6188b4a0288ac0ae4ae65f7a78b21b9b889f6e975d07efe09da2"
      }
    },
    {
      "assetId": "c06ea257-bec0-5ab5-9591-cab5f74a667b",
      "stockKey": "stk.clinic.dental.orthodontic.6627598",
      "origin": "licensed_stock",
      "providerAssetId": "6627598",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627598.webp",
      "alt": "Close-up image of a dental shade guide displaying various tooth color options.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/samples-of-teeth-6627598/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "04618fd1c2fa4afa4498817357c753c258d2d202d58ea53b61d7ca9a4ff9a0ae"
      }
    },
    {
      "assetId": "679b913d-07ad-5d2c-be69-b7f2921be2fb",
      "stockKey": "stk.clinic.dental.orthodontic.6627601",
      "origin": "licensed_stock",
      "providerAssetId": "6627601",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627601.webp",
      "alt": "Close-up of dental molds on a white table, showcasing orthodontic details.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/dental-teeth-cast-models-on-table-6627601/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "dae48a77f3f3a5a92848aaad111a5a739857e3f12b74ad8d11adeaee6345cf3f"
      }
    },
    {
      "assetId": "f85041a6-7e3d-5b57-9f8c-0ab7bbf0845b",
      "stockKey": "stk.clinic.dental.orthodontic.6627604",
      "origin": "licensed_stock",
      "providerAssetId": "6627604",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627604.webp",
      "alt": "Close-up of a dental shade guide used for tooth color matching in dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-artificial-teeth-6627604/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "0ac8a982cb8cc5da0882102d9d0dc98da7b0d4acf789c512573159c7124d9a5a"
      }
    },
    {
      "assetId": "4eaeb913-7438-53cd-9ad4-4a9f5b80c64c",
      "stockKey": "stk.clinic.dental.orthodontic.6627689",
      "origin": "licensed_stock",
      "providerAssetId": "6627689",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627689.webp",
      "alt": "Close-up of various dental tools and models used for dentistry displayed on a table.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/dentist-equipments-on-the-table-6627689/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "1ae35ebf40a8e79e73b90e5347e2947d26628c2c630ab91d59c77b8fcbb1c3a6"
      }
    },
    {
      "assetId": "951fcce7-1891-5d2d-be93-e0846de8a53d",
      "stockKey": "stk.clinic.dental.orthodontic.6627691",
      "origin": "licensed_stock",
      "providerAssetId": "6627691",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627691.webp",
      "alt": "Close-up of dental instruments and tooth models on a clinic table for dental care procedures.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/a-close-up-shot-of-a-dental-cast-and-medical-instruments-6627691/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d8cc25ace3b2a02970ac555e8d77464099d5039c16c3118e13603f5120aa9d69"
      }
    },
    {
      "assetId": "eedd155f-eb86-5535-98f7-351da5bc4803",
      "stockKey": "stk.clinic.dental.orthodontic.6627694",
      "origin": "licensed_stock",
      "providerAssetId": "6627694",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627694.webp",
      "alt": "Close-up of colorful dental endodontic files arranged in a sterilization tray for dentistry use.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-medical-samples-6627694/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "0d04e1049515ed0f6d41ea3f57418f67230113deceb94d73fc134ee991007cf7"
      }
    },
    {
      "assetId": "a83b5baa-98bb-5f15-9834-e6618855cd7e",
      "stockKey": "stk.clinic.dental.orthodontic.6627695",
      "origin": "licensed_stock",
      "providerAssetId": "6627695",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627695.webp",
      "alt": "A set of dental tools neatly arranged on a blue mat, emphasizing modern dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/stainless-steel-tray-on-the-table-6627695/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "0c64d5e104456cbbb332a6d254b63d223010d4756065a29d3165941aebaab379"
      }
    },
    {
      "assetId": "1fa150a3-5196-5006-89f5-669b2304dbdb",
      "stockKey": "stk.clinic.dental.orthodontic.6627715",
      "origin": "licensed_stock",
      "providerAssetId": "6627715",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627715.webp",
      "alt": "Dental jaw model with dental tools on a blue cloth for dental education and practice.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/jaw-models-with-teeth-6627715/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "9dc326e6e76b09aaa9edbc05cad9e088bab1f1b36bff159fbdaa394f925410bc"
      }
    },
    {
      "assetId": "e76b761c-826d-5960-bf97-b3f4f24c6b4f",
      "stockKey": "stk.clinic.dental.orthodontic.6627724",
      "origin": "licensed_stock",
      "providerAssetId": "6627724",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627724.webp",
      "alt": "Detailed view of dental equipment and models on a sterile blue background in a healthcare setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-dentist-equipment-6627724/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "1379c36488c12f3cf9959a47e09b613613092c4f14ce17ecf215e33b2cfdc46e"
      }
    },
    {
      "assetId": "4dbe1004-7162-5070-8712-51a0eb01b18b",
      "stockKey": "stk.clinic.dental.orthodontic.6627725",
      "origin": "licensed_stock",
      "providerAssetId": "6627725",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627725.webp",
      "alt": "Close-up of dental tools and accessories in a clinic setting, showcasing a modern and clean environment.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-dental-instruments-on-table-6627725/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "f18d97b1c27e510a67fda98952760fb40ec2af3f6e3c7ff28d454daeab425298"
      }
    },
    {
      "assetId": "b5976685-25e0-5be3-93fd-5d93cec64ba4",
      "stockKey": "stk.clinic.dental.orthodontic.6627733",
      "origin": "licensed_stock",
      "providerAssetId": "6627733",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627733.webp",
      "alt": "Sterile dental tools arranged on metal trays for dental procedures.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/dental-steel-instruments-6627733/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "9c558efbb38db4a589ff090f8fbc95e022097074283ce9a365653bcb2949d867"
      }
    },
    {
      "assetId": "0117d659-105c-5a1f-ac74-289ec9d74517",
      "stockKey": "stk.clinic.dental.orthodontic.7422519",
      "origin": "licensed_stock",
      "providerAssetId": "7422519",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/7422519.webp",
      "alt": "Close-up image showing detailed dental models and dentures on display, ideal for dental education.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Emeric Kalil",
        "photographerUrl": "https://www.pexels.com/@emerickalil",
        "sourceUrl": "https://www.pexels.com/photo/teeth-and-dental-cast-models-7422519/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "39f6e6c3dbf5f14f83c1f4f6cf63e1fc9a4cb8d49638df89c9d5ac4e9067d943"
      }
    },
    {
      "assetId": "40cd26e0-ec63-5def-9534-7501b21cb88d",
      "stockKey": "stk.clinic.dental.orthodontic.13085186",
      "origin": "licensed_stock",
      "providerAssetId": "13085186",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/13085186.webp",
      "alt": "A dental technician uses a grinder to polish a clear aligner in a laboratory setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "helia ghaharian",
        "photographerUrl": "https://www.pexels.com/@helia-ghaharian-43042372",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-a-dental-technician-making-an-invisalign-13085186/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "38099edc944fac3bbd2037d13eb6ff9fcb88f33239c42c800738ef439dfdf7ac"
      }
    },
    {
      "assetId": "ef964430-3d9c-5f67-84c9-9eadc75c8d11",
      "stockKey": "stk.clinic.dental.orthodontic.16309612",
      "origin": "licensed_stock",
      "providerAssetId": "16309612",
      "category": "orthodontic",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/16309612.webp",
      "alt": "Close-up of a dental model held by gloved hands in a laboratory setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Numan Gilgil",
        "photographerUrl": "https://www.pexels.com/@numangilgil",
        "sourceUrl": "https://www.pexels.com/photo/hand-in-glove-holding-jaw-with-teeth-16309612/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d1bed214b083c7afa3de99d4660a8b05dffcad2f899bbb15f5962edc65744e09"
      }
    },
    {
      "assetId": "33ce70fe-4ae1-599c-adcc-93e060bc79a1",
      "stockKey": "stk.clinic.dental.preventive-general.3881237",
      "origin": "licensed_stock",
      "providerAssetId": "3881237",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/3881237.webp",
      "alt": "From above view of crop unrecognizable medical specialist in latex gloves holding plastic containers with metal heads of dental drill during work in modern clinic",
      "attribution": {
        "provider": "pexels",
        "photographer": "Andrea Piacquadio",
        "photographerUrl": "https://www.pexels.com/@olly",
        "sourceUrl": "https://www.pexels.com/photo/crop-unrecognizable-dentist-preparing-medical-equipment-in-clinic-3881237/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "db5cf85abddf35349865472392f7fab28a5ed504c334e24f752cfeab89dc121a"
      }
    },
    {
      "assetId": "12a96009-9292-5b33-9428-bbecbb75bf75",
      "stockKey": "stk.clinic.dental.preventive-general.3881402",
      "origin": "licensed_stock",
      "providerAssetId": "3881402",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/3881402.webp",
      "alt": "Anonymous medical specialist in latex gloves using forceps to take detail from plastic container while working in modern clinic",
      "attribution": {
        "provider": "pexels",
        "photographer": "Andrea Piacquadio",
        "photographerUrl": "https://www.pexels.com/@olly",
        "sourceUrl": "https://www.pexels.com/photo/unrecognizable-crop-dentist-taking-detail-with-forceps-in-modern-clinic-3881402/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "9d7afda0bc088322d0c52d662b10c1cfa1eaa749a784efaf6b8962d00c74b1fc"
      }
    },
    {
      "assetId": "584df011-a844-5fcb-9181-fd1086905fb6",
      "stockKey": "stk.clinic.dental.preventive-general.4269356",
      "origin": "licensed_stock",
      "providerAssetId": "4269356",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269356.webp",
      "alt": "Close-up of various colorful dental tools on a light green background, ideal for dental care visuals.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-dental-tools-4269356/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "df9d0a6c442d195c76d2d1268417207d8536cc9b9f631d01ab24ac81e368c932"
      }
    },
    {
      "assetId": "21483069-3467-56f6-8210-249d2db15851",
      "stockKey": "stk.clinic.dental.preventive-general.4270967",
      "origin": "licensed_stock",
      "providerAssetId": "4270967",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4270967.webp",
      "alt": "Top view of various dental instruments arranged on a tray, ideal for medical use.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/stainless-steel-dental-tools-on-the-white-surface-4270967/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "f52cb91b712804e4a8387a8198cdf25f31a131e90e49262b5e4d2a70b885bd13"
      }
    },
    {
      "assetId": "181c3ff2-1d8f-5eab-a6db-61f879ecf409",
      "stockKey": "stk.clinic.dental.preventive-general.4270969",
      "origin": "licensed_stock",
      "providerAssetId": "4270969",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4270969.webp",
      "alt": "A set of shiny stainless steel dental tools neatly arranged on a blue cloth.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/stainless-steel-medical-tools-4270969/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "2daa1a4171a1ba65b2cd8fb26e918aa08fa38eecb46531854441b7a9c545ae8f"
      }
    },
    {
      "assetId": "3ab5fd05-97d9-56e5-8e57-2d89427178fd",
      "stockKey": "stk.clinic.dental.preventive-general.4946338",
      "origin": "licensed_stock",
      "providerAssetId": "4946338",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4946338.webp",
      "alt": "Close-up of stainless steel dental tools arranged on a bright blue surface, showcasing various instruments.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Marta Branco",
        "photographerUrl": "https://www.pexels.com/@martabranco",
        "sourceUrl": "https://www.pexels.com/photo/dental-tools-on-blue-surface-4946338/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "5f7d1fe0171a0383867825aa3e738642128064887777a2c9d83c68540f80919b"
      }
    },
    {
      "assetId": "a89855d6-f102-5ad3-a17e-3efbf4aaa083",
      "stockKey": "stk.clinic.dental.preventive-general.5355858",
      "origin": "licensed_stock",
      "providerAssetId": "5355858",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355858.webp",
      "alt": "A clean and modern dental clinic featuring a blue dental chair, equipment, and sterile supplies.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/dental-facility-5355858/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "8998f8399b55802acd686cac4198b73698644f3345fafb06f82c304e65f9be54"
      }
    },
    {
      "assetId": "9af61569-8867-5f0c-9158-602332facb94",
      "stockKey": "stk.clinic.dental.preventive-general.5355917",
      "origin": "licensed_stock",
      "providerAssetId": "5355917",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355917.webp",
      "alt": "Close-up of modern dental instruments in a clinic, highlighting advanced technology in dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-a-machine-with-dental-instruments-at-the-dentists-office-5355917/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "18c1be61f323e42ebdbb8195fe55ed2e2e4a6845c4ffb59416da640f659fca6d"
      }
    },
    {
      "assetId": "3327850b-2aa2-5f1e-9eb6-0ee2d6743e21",
      "stockKey": "stk.clinic.dental.preventive-general.5355920",
      "origin": "licensed_stock",
      "providerAssetId": "5355920",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355920.webp",
      "alt": "Bright and clean dental clinic interior showcasing a dental chair and equipment.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/a-clinic-with-dental-equipment-5355920/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "91a881ddd5c20410b58f7aaea5a3806100628ddb47bacb96c127e00962cf03bf"
      }
    },
    {
      "assetId": "8f4252d6-9e0f-570f-8284-150b52590af3",
      "stockKey": "stk.clinic.dental.preventive-general.6502295",
      "origin": "licensed_stock",
      "providerAssetId": "6502295",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502295.webp",
      "alt": "Close-up of dental tools and test tubes on a blue surface, highlighting modern medical equipment.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-pliers-and-test-tubes-on-blue-surface-6502295/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "461a19c7f8c39437c36c3d260ae9ddc28b6cd808c71480ff1d7261336d5acc3e"
      }
    },
    {
      "assetId": "5b318ce1-3607-5e53-8ea8-275d81f04d78",
      "stockKey": "stk.clinic.dental.preventive-general.6502338",
      "origin": "licensed_stock",
      "providerAssetId": "6502338",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502338.webp",
      "alt": "Detailed image of sterile dental equipment used in modern dentistry and healthcare settings.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/dental-tools-and-equipment-in-close-up-photography-6502338/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "4a9434d6b366f8cfb4f9287139063a3108386b0087d1f9fb9123344ef5f07a8b"
      }
    },
    {
      "assetId": "642d331e-ba19-546f-96f5-2206034629d2",
      "stockKey": "stk.clinic.dental.preventive-general.6502344",
      "origin": "licensed_stock",
      "providerAssetId": "6502344",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502344.webp",
      "alt": "Close-up of dental equipment with handpieces, showcasing modern dental care tools in a clinic.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-dental-handpieces-6502344/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "4727a9e5bc3b7ba4ea424c321d8435fb4036070aa6a6e2de03dd00b6cb493842"
      }
    },
    {
      "assetId": "a10d1e40-9945-58c2-a319-22f148003ef5",
      "stockKey": "stk.clinic.dental.preventive-general.6502543",
      "origin": "licensed_stock",
      "providerAssetId": "6502543",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502543.webp",
      "alt": "Close-up of advanced dental chair setup with dental instruments in a clinic.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-dental-handpieces-6502543/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "164be18656c5a967e8e0b00b6cc27b1ba5863ce598a56f22a0f2c11e2b3ec459"
      }
    },
    {
      "assetId": "afb43f5f-9938-52b9-9728-524d7b2b1c78",
      "stockKey": "stk.clinic.dental.preventive-general.6502557",
      "origin": "licensed_stock",
      "providerAssetId": "6502557",
      "category": "preventive-general",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6502557.webp",
      "alt": "Close-up of modern dental equipment featuring cords and instruments in a clinic.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/dental-equipment-in-close-up-photography-6502557/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "a4e213449535c9178444a6f2a7f53481bfe0170a87a239095a1d1bcba01c115a"
      }
    },
    {
      "assetId": "8b899fd2-a1cf-5d34-89c1-4c88fd94a05d",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.4562896",
      "origin": "licensed_stock",
      "providerAssetId": "4562896",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4562896.webp",
      "alt": "Sleek and modern dental equipment setup in a clinical environment, perfect for dentistry themes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Engin Akyurt",
        "photographerUrl": "https://www.pexels.com/@enginakyurt",
        "sourceUrl": "https://www.pexels.com/photo/dentals-tools-attached-to-a-dental-engine-4562896/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d3c82b7f816683014395ce241225df364aa981c7798485611a85ff7829dd8cc4"
      }
    },
    {
      "assetId": "7d6de087-ff76-5c74-af75-9d0e53d3d2fc",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.5355919",
      "origin": "licensed_stock",
      "providerAssetId": "5355919",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355919.webp",
      "alt": "Assortment of dental tools and devices on a clinic table.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/various-dental-tools-on-a-dental-table-5355919/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "bf6dc7655af9957b2a9e5db5061d0f221a4faa28b480ba3a6039b90f0f6bfd63"
      }
    },
    {
      "assetId": "7bef9519-1afb-5044-9822-39eddacf1789",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627600",
      "origin": "licensed_stock",
      "providerAssetId": "6627600",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627600.webp",
      "alt": "Dentist wearing gloves polishes a dental prosthetic using a specialized tool in a clinical setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/hands-in-gloves-polishing-teeth-implants-6627600/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "8368d398c0017df656fb48ed363763e2816bbe7c4c0546b445fdd1ca9cd3df02"
      }
    },
    {
      "assetId": "292be001-f90d-585d-8eb2-b77aea50c908",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627654",
      "origin": "licensed_stock",
      "providerAssetId": "6627654",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627654.webp",
      "alt": "Modern dental machinery for precise dentistry procedures; ideal for healthcare professionals.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/machine-for-dental-treatment-6627654/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "43277af95088659aa36d98e0f3b3f10a9b069173d92709c55b19bca805cd6f31"
      }
    },
    {
      "assetId": "e77322a1-9d4d-5a7e-84f9-0901e8cea12f",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627663",
      "origin": "licensed_stock",
      "providerAssetId": "6627663",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627663.webp",
      "alt": "Close-up of dental machine and denture on countertop, showcasing dental technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/a-denture-beside-a-medical-equipment-6627663/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "a441395c319537afc93731a6640fe4092411d1ae1bca2e3ec3e64ca83126b52b"
      }
    },
    {
      "assetId": "f042d273-06f6-58c1-87ec-add58e5df5ae",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627664",
      "origin": "licensed_stock",
      "providerAssetId": "6627664",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627664.webp",
      "alt": "Close-up of operator using sterilization machine in a medical facility.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/a-dentist-using-an-autoclave-machine-6627664/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "09d32a4691f298c669b32b6f65ab24f252132dd8dc6893865a176cbc18da7f9f"
      }
    },
    {
      "assetId": "67e3f0dc-71d9-548b-9ec6-1467f637c3cf",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627668",
      "origin": "licensed_stock",
      "providerAssetId": "6627668",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627668.webp",
      "alt": "High-tech dental tools and instruments in a dental clinic setting, showcasing advanced healthcare technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/a-close-up-shot-of-dental-equipment-6627668/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "388b8af9d72b4c8f7f4c9b6879a90390fe8b1e1b5306953e100f4268169a3a23"
      }
    },
    {
      "assetId": "c8de4a4e-9c63-5b53-b89e-a3f63b2ebc01",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627669",
      "origin": "licensed_stock",
      "providerAssetId": "6627669",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627669.webp",
      "alt": "Dental instruments on a silver tray, ideal for illustrating medical and dental themes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/a-close-up-shot-of-dental-medical-instruments-on-a-silver-tray-6627669/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d0818046b0ea2eae74e46cb3aa6b39548953cd818426332cb0aac652aa7b8496"
      }
    },
    {
      "assetId": "d6c66818-7d1a-529a-962e-b51f1631d74d",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627671",
      "origin": "licensed_stock",
      "providerAssetId": "6627671",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627671.webp",
      "alt": "Close-up of dental tools on a clean, sterile metal tray, emphasizing hygiene and precision.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-sterile-instruments-on-medical-tray-6627671/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "951a75aec16df140f7b12d9580b33466542b540102977bb84ea0a8ee15b16a4a"
      }
    },
    {
      "assetId": "1028c388-ba21-5a4b-9516-61b404159f20",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627704",
      "origin": "licensed_stock",
      "providerAssetId": "6627704",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627704.webp",
      "alt": "Close-up of sterilized surgical tools in packaging on a clinical table.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/sterile-instruments-on-table-6627704/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "58d12a44c9335593e370a6ce875448a814ea60f25b71ec6741de091cb2c79be4"
      }
    },
    {
      "assetId": "49963d43-e2af-5417-8961-4a8669441ba0",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627706",
      "origin": "licensed_stock",
      "providerAssetId": "6627706",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627706.webp",
      "alt": "A vibrant collection of dental tools displayed on a sterile blue cloth ready for dental use.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/dental-instruments-and-different-kinds-of-teeth-veneers-6627706/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "64f6306f3beddf3da201b60cb10ec24058adfa98d71d9acbba8efb61fc2bb07a"
      }
    },
    {
      "assetId": "04110cdf-863a-5c78-bd12-9cedceac4c0a",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6627722",
      "origin": "licensed_stock",
      "providerAssetId": "6627722",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6627722.webp",
      "alt": "A detailed view of dental instruments and materials arranged on a sterile blue surface in a clinical setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/top-view-of-dental-instruments-6627722/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "d158964412fbf6653cf88e67975348a3e2d2d96fdad36dd3ae24edaa2ca5bf67"
      }
    },
    {
      "assetId": "a3ade947-0d50-571a-8a05-15cd18f35b0c",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6629388",
      "origin": "licensed_stock",
      "providerAssetId": "6629388",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6629388.webp",
      "alt": "Detailed image of a medical endometer used in precision dental treatments, showcasing modern technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-an-endometer-6629388/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "6cbced095039b693efbebe0f4df761df33fc981f9b888e614e9a1736afd0574c"
      }
    },
    {
      "assetId": "6fd4a983-8950-525e-96e4-1aadb6a0f1a7",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6629389",
      "origin": "licensed_stock",
      "providerAssetId": "6629389",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6629389.webp",
      "alt": "A close-up view of dental machinery on a white table used in modern dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/dentist-equipment-on-white-table-6629389/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "71c4d7f4d0912a5a8df277ba82b52886175ad923216c2f6fdfbae2cdb3bccac5"
      }
    },
    {
      "assetId": "73886aa3-f6b7-5531-bcad-24747b23149d",
      "stockKey": "stk.clinic.dental.cosmetic-restorative.6629397",
      "origin": "licensed_stock",
      "providerAssetId": "6629397",
      "category": "cosmetic-restorative",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6629397.webp",
      "alt": "Close-up of a modern laboratory centrifuge on a sterile white surface, used in medical testing.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/laboratory-centrifuge-in-hospital-6629397/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "bc230a71457da6a02649be9112aa7805598d0805b803bba213354b9594692541"
      }
    },
    {
      "assetId": "8db5b50a-e578-54b8-9669-446a5439b5f1",
      "stockKey": "stk.clinic.dental.bright-interior.532786",
      "origin": "licensed_stock",
      "providerAssetId": "532786",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/532786.webp",
      "alt": "Close-up of dental chair and equipment in a clinical setting, emphasizing healthcare technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Fitusm Assefa",
        "photographerUrl": "https://www.pexels.com/@fitsumassefa",
        "sourceUrl": "https://www.pexels.com/photo/white-and-gray-hospital-chair-532786/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "5da18d8cd8d3e0a9f854c87d3c48a01f2127df3d00c1b14fddf897d78c96c570"
      }
    },
    {
      "assetId": "d2bff3c6-3c16-5caf-8aca-3b1cdfed6b6e",
      "stockKey": "stk.clinic.dental.bright-interior.4269268",
      "origin": "licensed_stock",
      "providerAssetId": "4269268",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269268.webp",
      "alt": "Stylish and modern dentist office with dental chair and equipment in a well-lit setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/back-view-of-a-dental-chair-in-a-clinic-4269268/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "4b8f9997344b7010c68205ead8c84ca47dacfffc00eec39f7a97febad14379e1"
      }
    },
    {
      "assetId": "518d76cd-4829-5296-80b9-2d6847c5eeaa",
      "stockKey": "stk.clinic.dental.bright-interior.4269277",
      "origin": "licensed_stock",
      "providerAssetId": "4269277",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4269277.webp",
      "alt": "Clean and organized dental office featuring a modern dental chair and equipment.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Cedric Fauntleroy",
        "photographerUrl": "https://www.pexels.com/@cedric-fauntleroy",
        "sourceUrl": "https://www.pexels.com/photo/side-view-of-a-dental-chair-in-a-clinic-4269277/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "b2c0fb246f68f523d7f4537927d66f339aa9d6872b52fe498721833bf55a4d4a"
      }
    },
    {
      "assetId": "9896dac1-0e22-5a19-8a2c-cf7bf63eb8c0",
      "stockKey": "stk.clinic.dental.bright-interior.4562895",
      "origin": "licensed_stock",
      "providerAssetId": "4562895",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/4562895.webp",
      "alt": "Bright and modern dental clinic with advanced equipment and comfortable seating area.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Engin Akyurt",
        "photographerUrl": "https://www.pexels.com/@enginakyurt",
        "sourceUrl": "https://www.pexels.com/photo/a-dental-engine-in-a-clinic-4562895/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "f937f6765e007c22ff36e5d57ded29d6c1e526e3f61404d8c8bebca108bdfac9"
      }
    },
    {
      "assetId": "5d610f55-bd1b-58dc-964d-349e5749d768",
      "stockKey": "stk.clinic.dental.bright-interior.5355863",
      "origin": "licensed_stock",
      "providerAssetId": "5355863",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/5355863.webp",
      "alt": "A clean and modern dental clinic featuring blue chairs and essential dental equipment.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tima Miroshnichenko",
        "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
        "sourceUrl": "https://www.pexels.com/photo/dental-facility-5355863/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "5179a14340b91567801e3dee4bc70d78ece380f78d2612b87e7cacdcd8927865"
      }
    },
    {
      "assetId": "1abf7d7e-85ce-5fda-bdb0-e94162468f19",
      "stockKey": "stk.clinic.dental.bright-interior.6501859",
      "origin": "licensed_stock",
      "providerAssetId": "6501859",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6501859.webp",
      "alt": "Close-up of modern dental x-ray machine in a clinic setting.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-dental-x-ray-machine-6501859/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "136741ba09b3e3679e84743afaf50cc9d1c3c964e8770aa19a36a1cb6ffeef30"
      }
    },
    {
      "assetId": "ef0e08f6-146a-5328-af89-68390cc372d9",
      "stockKey": "stk.clinic.dental.bright-interior.6501862",
      "origin": "licensed_stock",
      "providerAssetId": "6501862",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6501862.webp",
      "alt": "Monitor displaying dental X-ray images in a clinic setup for diagnostic purposes.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/an-x-ray-image-of-a-jawbone-in-the-computer-6501862/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "43d6d203add8310c76d881dd9985996434c059376e458c56b6f71cecbf44dc52"
      }
    },
    {
      "assetId": "abf60cc5-6ea6-535d-80aa-525ce3df8805",
      "stockKey": "stk.clinic.dental.bright-interior.6501868",
      "origin": "licensed_stock",
      "providerAssetId": "6501868",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6501868.webp",
      "alt": "Close-up of modern dental x-ray equipment in a clinic displaying advanced odontology technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-dental-x-ray-machine-6501868/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "1319ee57390239fa30a66c2ab3a3968df0a367cde393fee9c72246530dd48b1c"
      }
    },
    {
      "assetId": "89dd0503-cac7-5f1a-ab80-7549ff733531",
      "stockKey": "stk.clinic.dental.bright-interior.6629405",
      "origin": "licensed_stock",
      "providerAssetId": "6629405",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/6629405.webp",
      "alt": "Detailed view of a dental instrument used in dentistry, showcasing precise technology.",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-a-dental-instrument-6629405/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "29345c448dc037d5b76aaa6c19dd618210deb9a72753876f4c8ddccde5156823"
      }
    },
    {
      "assetId": "9fa22094-7386-5302-ae74-723e98d13f28",
      "stockKey": "stk.clinic.dental.bright-interior.38055771",
      "origin": "licensed_stock",
      "providerAssetId": "38055771",
      "category": "bright-interior",
      "width": 1600,
      "height": 1200,
      "renditionUrl": "/stock/pexels/dental-atmosphere/38055771.webp",
      "alt": "Bright and modern dental office interior in Beverly Hills, ideal workspace for cosmetic dentistry.",
      "attribution": {
        "provider": "pexels",
        "photographer": "Marc Chemla",
        "photographerUrl": "https://www.pexels.com/@marc-chemla-2162200115",
        "sourceUrl": "https://www.pexels.com/photo/modern-dental-office-interior-in-beverly-hills-38055771/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "clinic-dental-atmosphere-v1",
        "passed": true,
        "metadataSha256": "0a6cfdf0f122082d553a0ea1f2f9e555adc6232c9ed4056ba3f050a6e6d0e5bd"
      }
    }
  ]
} as const satisfies DentalStockManifest;
