import type {
  HeroLayoutAuthoredIndustry,
  HeroLayoutBandRecipe,
  HeroLayoutCompatibility,
  HeroLayoutIndustryAffinity,
  HeroLayoutSlotContract,
  HeroLayoutVariant,
  HeroLayoutVariantId,
} from './types';

const frame = (
  x: number,
  y: number,
  width: number,
  height: number,
) => ({ x, y, width, height } as const);

const slots = (maxChips: 2 | 3, mediaControl = false): readonly HeroLayoutSlotContract[] => [
  { id: 'logo', requirement: 'optional', maxItems: 1 },
  { id: 'eyebrow', requirement: 'optional', maxItems: 1 },
  { id: 'headline', requirement: 'required', maxItems: 1 },
  { id: 'lead', requirement: 'optional', maxItems: 1 },
  { id: 'chips', requirement: 'optional', maxItems: maxChips },
  { id: 'primary-cta', requirement: 'required', maxItems: 1 },
  { id: 'secondary-cta', requirement: 'optional', maxItems: 1 },
  ...(mediaControl
    ? [{ id: 'media-control', requirement: 'optional', maxItems: 1 } as const]
    : []),
];

const affinity = (
  recommended: readonly HeroLayoutAuthoredIndustry[],
  allowed: readonly HeroLayoutAuthoredIndustry[],
): Readonly<Record<HeroLayoutAuthoredIndustry, HeroLayoutIndustryAffinity>> => {
  const recommendedSet = new Set(recommended);
  const allowedSet = new Set(allowed);
  return Object.fromEntries([
    'cafe',
    'fine_dining',
    'beauty',
    'medical',
    'legal',
    'consulting',
    'workshop',
    'retail',
    'portfolio',
    'academy',
  ].map((industry) => [
    industry,
    recommendedSet.has(industry as HeroLayoutAuthoredIndustry)
      ? 'recommended'
      : allowedSet.has(industry as HeroLayoutAuthoredIndustry)
        ? 'allowed'
        : 'discouraged',
  ])) as Record<HeroLayoutAuthoredIndustry, HeroLayoutIndustryAffinity>;
};

const compatibility = (
  recommended: readonly HeroLayoutAuthoredIndustry[],
  allowed: readonly HeroLayoutAuthoredIndustry[],
  preferredDna: HeroLayoutCompatibility['preferredDna'],
  avoidedDna: HeroLayoutCompatibility['avoidedDna'],
): HeroLayoutCompatibility => ({
  industry: affinity(recommended, allowed),
  preferredDna,
  avoidedDna,
});

const recipe = (
  value: HeroLayoutBandRecipe,
): HeroLayoutBandRecipe => value;

export const HERO_LAYOUT_CATALOG = [
  {
    id: 'hero.fullbleed-centered',
    label: 'Centered full-bleed',
    description: 'Sets one scene and a short statement directly in front of the visitor.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'center-middle',
        contentColumns: [3, 10],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:10' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'center-middle',
        contentColumns: [2, 7],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:3' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'center-middle',
        contentColumns: [1, 4],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'atmospheric-background',
      categoricalEligible: false,
      // STK may add categorical-stock between the two authored steps.
      fallbackLadder: ['customer-referential', 'categorical-stock', 'system-atmospheric'],
      requirement: 'required-image',
      preferredAspect: { wide: '16:10', compact: '4:3', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'beauty', 'workshop', 'portfolio'],
      ['consulting', 'retail', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'cafe-warm-editorial',
        'workshop-tactile-heritage',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
  {
    id: 'hero.split-left',
    label: 'Information left, media right',
    description: 'Leads with explanation and action, with industry-relevant media on the right.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.52, 0.08, 0.42, 0.84), columns: [7, 12], aspect: '4:5' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.62, 0.14, 0.32, 0.72), columns: [6, 8], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'referential-figure',
      categoricalEligible: true,
      fallbackLadder: ['customer-referential', 'categorical-stock', 'collapse-slot'],
      requirement: 'optional-image',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['cafe', 'beauty', 'medical', 'legal', 'consulting', 'academy'],
      ['fine_dining', 'workshop', 'retail', 'portfolio'],
      [
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'cafe-warm-editorial',
        'beauty-soft-wellness',
        'academy-structured-friendly',
      ],
      ['retail-bold-geometric'],
    ),
  },
  {
    id: 'hero.split-right',
    label: 'Media left, information right',
    description: 'Lets the image lead into a short information block on the right.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'end-middle',
        contentColumns: [7, 12],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.84), columns: [1, 6], aspect: '4:5' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'end-middle',
        contentColumns: [4, 8],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.06, 0.14, 0.32, 0.72), columns: [1, 3], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'referential-figure',
      categoricalEligible: true,
      fallbackLadder: ['customer-referential', 'categorical-stock', 'collapse-slot'],
      requirement: 'optional-image',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'consulting', 'workshop', 'portfolio'],
      ['cafe', 'medical', 'legal', 'retail', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity'],
    ),
  },
  {
    id: 'hero.overlay-bottom-left',
    label: 'Lower-left overlay',
    description: 'Keeps the center of the scene open and places the statement and action at lower left.',
    slots: slots(2),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-lower',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:10' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-lower',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:3' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'start-lower',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'atmospheric-background',
      categoricalEligible: false,
      // Atmospheric categorical eligibility is a separate STK axis from figure eligibility.
      fallbackLadder: ['customer-referential', 'categorical-stock', 'system-atmospheric'],
      requirement: 'required-image',
      preferredAspect: { wide: '16:10', compact: '4:3', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'workshop', 'retail', 'portfolio'],
      ['beauty', 'consulting'],
      [
        'cafe-warm-editorial',
        'dining-refined-contrast',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
  {
    id: 'hero.video-scrim',
    label: 'Video or poster with scrim',
    description: 'Uses a real scene as the background and remains complete with a static poster.',
    slots: slots(2, true),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'start-lower',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'atmospheric-background',
      categoricalEligible: false,
      fallbackLadder: ['customer-video-poster', 'system-atmospheric'],
      requirement: 'required-video-poster',
      preferredAspect: { wide: '16:9', compact: '16:9', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'workshop', 'retail', 'portfolio'],
      ['cafe', 'consulting'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
      ],
      [
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
    ),
  },
  {
    id: 'hero.text-only-bold',
    label: 'Bold typography without media',
    description: 'Builds hierarchy around a verifiable statement and name without requiring an image.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'flow-full',
        contentColumns: [1, 12],
        slotColumns: {
          eyebrow: [1, 4],
          headline: [1, 11],
          lead: [8, 12],
          chips: [1, 7],
          'primary-cta': [1, 6],
          'secondary-cta': [1, 6],
        },
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'flow-full',
        contentColumns: [1, 8],
        slotColumns: {
          headline: [1, 8],
          lead: [3, 8],
          chips: [1, 8],
          'primary-cta': [1, 8],
          'secondary-cta': [1, 8],
        },
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-full',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'none',
      categoricalEligible: false,
      fallbackLadder: [],
      requirement: 'none',
      preferredAspect: {},
      focusPolicy: 'none',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['medical', 'legal', 'consulting', 'retail', 'portfolio', 'academy'],
      ['cafe', 'fine_dining', 'beauty', 'workshop'],
      [
        'legal-authoritative-editorial',
        'medical-clinical-clarity',
        'retail-bold-geometric',
        'academy-structured-friendly',
      ],
      ['beauty-soft-wellness'],
    ),
  },
  {
    id: 'hero.image-below',
    label: 'Text above, image below',
    description: 'Presents the promise and action before a wide supporting image.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'flow-start',
        contentColumns: [1, 7],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 8], aspect: '3:1' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'flow-start',
        contentColumns: [1, 6],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 8], aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      role: 'referential-figure',
      categoricalEligible: true,
      fallbackLadder: ['customer-referential', 'categorical-stock', 'collapse-slot'],
      requirement: 'optional-image',
      preferredAspect: { wide: '3:1', compact: '16:9', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'beauty', 'medical', 'legal', 'consulting', 'workshop', 'portfolio', 'academy'],
      ['retail'],
      [
        'cafe-warm-editorial',
        'dining-refined-contrast',
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
      ['retail-bold-geometric'],
    ),
  },
  {
    id: 'hero.asymmetric-offset',
    label: 'Asymmetric offset',
    description: 'Offsets the starting heights of media and text to create an editorial rhythm.',
    slots: slots(2),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'end-middle',
        contentColumns: [7, 12],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.72), columns: [1, 6], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'surface-offset',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'center-middle',
        contentColumns: [5, 8],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.56), columns: [1, 4], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'surface-offset',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-full',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', columns: [1, 3.5], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'surface-offset',
      }),
    },
    mediaContract: {
      role: 'referential-figure',
      categoricalEligible: true,
      fallbackLadder: ['customer-referential', 'categorical-stock', 'collapse-slot'],
      requirement: 'optional-image',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'workshop', 'retail', 'portfolio'],
      ['cafe', 'consulting', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
] as const satisfies readonly HeroLayoutVariant[];

export function heroLayoutById(
  id: HeroLayoutVariantId,
): HeroLayoutVariant {
  const variant = HERO_LAYOUT_CATALOG.find((candidate) => candidate.id === id);
  if (!variant) throw new Error(`Unknown hero layout variant: ${id}`);
  return variant;
}
