import type {
  HeroLayoutAuthoredIndustry,
  HeroLayoutBandRecipe,
  HeroLayoutCompatibility,
  HeroLayoutIndustryAffinity,
  HeroLayoutSlotContract,
  HeroLayoutVariant,
  HeroLayoutVariantId,
} from './types';

const frame = (
  x: number,
  y: number,
  width: number,
  height: number,
) => ({ x, y, width, height } as const);

const slots = (maxChips: 2 | 3, mediaControl = false): readonly HeroLayoutSlotContract[] => [
  { id: 'logo', requirement: 'optional', maxItems: 1 },
  { id: 'eyebrow', requirement: 'optional', maxItems: 1 },
  { id: 'headline', requirement: 'required', maxItems: 1 },
  { id: 'lead', requirement: 'optional', maxItems: 1 },
  { id: 'chips', requirement: 'optional', maxItems: maxChips },
  { id: 'primary-cta', requirement: 'required', maxItems: 1 },
  { id: 'secondary-cta', requirement: 'optional', maxItems: 1 },
  ...(mediaControl
    ? [{ id: 'media-control', requirement: 'optional', maxItems: 1 } as const]
    : []),
];

const affinity = (
  recommended: readonly HeroLayoutAuthoredIndustry[],
  allowed: readonly HeroLayoutAuthoredIndustry[],
): Readonly<Record<HeroLayoutAuthoredIndustry, HeroLayoutIndustryAffinity>> => {
  const recommendedSet = new Set(recommended);
  const allowedSet = new Set(allowed);
  return Object.fromEntries([
    'cafe',
    'fine_dining',
    'beauty',
    'medical',
    'legal',
    'consulting',
    'workshop',
    'retail',
    'portfolio',
    'academy',
  ].map((industry) => [
    industry,
    recommendedSet.has(industry as HeroLayoutAuthoredIndustry)
      ? 'recommended'
      : allowedSet.has(industry as HeroLayoutAuthoredIndustry)
        ? 'allowed'
        : 'discouraged',
  ])) as Record<HeroLayoutAuthoredIndustry, HeroLayoutIndustryAffinity>;
};

const compatibility = (
  recommended: readonly HeroLayoutAuthoredIndustry[],
  allowed: readonly HeroLayoutAuthoredIndustry[],
  preferredDna: HeroLayoutCompatibility['preferredDna'],
  avoidedDna: HeroLayoutCompatibility['avoidedDna'],
): HeroLayoutCompatibility => ({
  industry: affinity(recommended, allowed),
  preferredDna,
  avoidedDna,
});

const recipe = (
  value: HeroLayoutBandRecipe,
): HeroLayoutBandRecipe => value;

export const HERO_LAYOUT_CATALOG = [
  {
    id: 'hero.fullbleed-centered',
    label: '풀블리드 중앙 집중형',
    description: '공간·제품의 한 장면과 짧은 선언을 정면에서 함께 각인합니다.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'center-middle',
        contentColumns: [3, 10],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:10' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'center-middle',
        contentColumns: [2, 7],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:3' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'center-middle',
        contentColumns: [1, 4],
        align: 'center',
        flow: 'center-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'required-image',
      noMediaFallback: 'hero.text-only-bold',
      preferredAspect: { wide: '16:10', compact: '4:3', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'beauty', 'workshop', 'portfolio'],
      ['consulting', 'retail', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'cafe-warm-editorial',
        'workshop-tactile-heritage',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
  {
    id: 'hero.split-left',
    label: '좌측 정보·우측 미디어형',
    description: '설명과 전환을 먼저 읽히게 하면서 우측에 업종 이미지를 병치합니다.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.52, 0.08, 0.42, 0.84), columns: [7, 12], aspect: '4:5' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.62, 0.14, 0.32, 0.72), columns: [6, 8], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'optional-image',
      noMediaFallback: 'self-without-media',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['cafe', 'beauty', 'medical', 'legal', 'consulting', 'academy'],
      ['fine_dining', 'workshop', 'retail', 'portfolio'],
      [
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'cafe-warm-editorial',
        'beauty-soft-wellness',
        'academy-structured-friendly',
      ],
      ['retail-bold-geometric'],
    ),
  },
  {
    id: 'hero.split-right',
    label: '좌측 미디어·우측 정보형',
    description: '이미지가 먼저 시선을 잡고 우측의 짧은 정보 블록으로 전환되게 합니다.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'end-middle',
        contentColumns: [7, 12],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.84), columns: [1, 6], aspect: '4:5' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'end-middle',
        contentColumns: [4, 8],
        align: 'start',
        flow: 'split',
        media: { placement: 'fixed', frame: frame(0.06, 0.14, 0.32, 0.72), columns: [1, 3], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'optional-image',
      noMediaFallback: 'self-without-media',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'consulting', 'workshop', 'portfolio'],
      ['cafe', 'medical', 'legal', 'retail', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity'],
    ),
  },
  {
    id: 'hero.overlay-bottom-left',
    label: '하단 좌측 오버레이형',
    description: '장면의 중앙을 비우고 핵심 문장과 전환을 하단 좌측에 압축합니다.',
    slots: slots(2),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-lower',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:10' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-lower',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:3' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'start-lower',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'lower-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'required-image',
      noMediaFallback: 'hero.text-only-bold',
      preferredAspect: { wide: '16:10', compact: '4:3', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'workshop', 'retail', 'portfolio'],
      ['beauty', 'consulting'],
      [
        'cafe-warm-editorial',
        'dining-refined-contrast',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
  {
    id: 'hero.video-scrim',
    label: '영상·포스터 스크림형',
    description: '실제 장면을 배경으로 쓰되 정적 포스터만으로도 완성되는 히어로입니다.',
    slots: slots(2, true),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'start-middle',
        contentColumns: [1, 5],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'start-lower',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'video-overlay',
        media: { placement: 'fullbleed', frame: frame(0, 0, 1, 1), aspect: '4:5' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'required-video-poster',
      noMediaFallback: 'hero.text-only-bold',
      posterOnlyFallback: 'hero.fullbleed-centered',
      preferredAspect: { wide: '16:9', compact: '16:9', mobile: '4:5' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'subtle-scrim',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'workshop', 'retail', 'portfolio'],
      ['cafe', 'consulting'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
      ],
      [
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
    ),
  },
  {
    id: 'hero.text-only-bold',
    label: '이미지 없는 볼드 타이포형',
    description: '검증 가능한 문장과 이름 자체를 중심으로 이미지 없이 위계를 만듭니다.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'flow-full',
        contentColumns: [1, 12],
        slotColumns: {
          eyebrow: [1, 4],
          headline: [1, 11],
          lead: [8, 12],
          chips: [1, 7],
          'primary-cta': [1, 6],
          'secondary-cta': [1, 6],
        },
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'flow-full',
        contentColumns: [1, 8],
        slotColumns: {
          headline: [1, 8],
          lead: [3, 8],
          chips: [1, 8],
          'primary-cta': [1, 8],
          'secondary-cta': [1, 8],
        },
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-full',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'editorial-flow',
        media: { placement: 'none' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'none',
      noMediaFallback: 'self-without-media',
      preferredAspect: {},
      focusPolicy: 'none',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['medical', 'legal', 'consulting', 'retail', 'portfolio', 'academy'],
      ['cafe', 'fine_dining', 'beauty', 'workshop'],
      [
        'legal-authoritative-editorial',
        'medical-clinical-clarity',
        'retail-bold-geometric',
        'academy-structured-friendly',
      ],
      ['beauty-soft-wellness'],
    ),
  },
  {
    id: 'hero.image-below',
    label: '텍스트 상단·이미지 하단형',
    description: '약속과 행동을 먼저 읽힌 뒤 넓은 이미지로 근거 장면을 보여줍니다.',
    slots: slots(3),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'flow-start',
        contentColumns: [1, 7],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 8], aspect: '3:1' },
        chipItemsPerRow: 3,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'flow-start',
        contentColumns: [1, 6],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 8], aspect: '16:9' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'none',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-start',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'media-after',
        media: { placement: 'after-flow', columns: [1, 4], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'none',
      }),
    },
    mediaContract: {
      requirement: 'optional-image',
      noMediaFallback: 'self-without-media',
      preferredAspect: { wide: '3:1', compact: '16:9', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['cafe', 'fine_dining', 'beauty', 'medical', 'legal', 'consulting', 'workshop', 'portfolio', 'academy'],
      ['retail'],
      [
        'cafe-warm-editorial',
        'dining-refined-contrast',
        'medical-clinical-clarity',
        'legal-authoritative-editorial',
        'academy-structured-friendly',
      ],
      ['retail-bold-geometric'],
    ),
  },
  {
    id: 'hero.asymmetric-offset',
    label: '비대칭 오프셋형',
    description: '미디어와 텍스트 패널의 시작 높이를 달리해 편집적인 리듬을 만듭니다.',
    slots: slots(2),
    bands: {
      wide: recipe({
        gridColumns: 12,
        textZone: 'end-middle',
        contentColumns: [7, 12],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.72), columns: [1, 6], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'surface-offset',
      }),
      compact: recipe({
        gridColumns: 8,
        textZone: 'center-middle',
        contentColumns: [5, 8],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', frame: frame(0.06, 0.08, 0.42, 0.56), columns: [1, 4], aspect: '4:5' },
        chipItemsPerRow: 2,
        ctaLayout: 'wrap',
        panel: 'surface-offset',
      }),
      mobile: recipe({
        gridColumns: 4,
        textZone: 'flow-full',
        contentColumns: [1, 4],
        align: 'start',
        flow: 'offset-surface',
        media: { placement: 'fixed', columns: [1, 3.5], aspect: '4:3' },
        chipItemsPerRow: 1,
        ctaLayout: 'stack',
        panel: 'surface-offset',
      }),
    },
    mediaContract: {
      requirement: 'optional-image',
      noMediaFallback: 'self-without-media',
      preferredAspect: { wide: '4:5', compact: '4:5', mobile: '4:3' },
      focusPolicy: 'clamped-safe-zone-aware',
    },
    scrim: 'none',
    compatibility: compatibility(
      ['fine_dining', 'beauty', 'workshop', 'retail', 'portfolio'],
      ['cafe', 'consulting', 'academy'],
      [
        'dining-refined-contrast',
        'beauty-soft-wellness',
        'workshop-tactile-heritage',
        'retail-bold-geometric',
        'academy-structured-friendly',
      ],
      ['medical-clinical-clarity', 'legal-authoritative-editorial'],
    ),
  },
] as const satisfies readonly HeroLayoutVariant[];

export function heroLayoutById(
  id: HeroLayoutVariantId,
): HeroLayoutVariant {
  const variant = HERO_LAYOUT_CATALOG.find((candidate) => candidate.id === id);
  if (!variant) throw new Error(`Unknown hero layout variant: ${id}`);
  return variant;
}

