/**
 * Existing frozen renditions can be enriched without calling Pexels again.
 * The sync timestamp and provider metadata stay unchanged; only deterministic
 * image-channel-range profiles are regenerated from repository-owned bytes.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { assessImageContrastProfile } from '../src/lib/assets/image-contrast-profile';
import { workshopStockManifest } from '../src/lib/stock/manifest';
import type { FrozenStockManifest } from '../src/lib/stock/types';

const MANIFEST_PATH = path.resolve('src/lib/stock/workshop-manifest.generated.ts');

function manifestSource(manifest: FrozenStockManifest): string {
  return [
    "import type { FrozenStockManifest } from './types';",
    '',
    '/** Generated by scripts/sync-pexels-stock.ts; public rendering never calls Pexels. */',
    `export const WORKSHOP_STOCK_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const satisfies FrozenStockManifest;`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const current = workshopStockManifest();
  const assets = await Promise.all(current.assets.map(async (asset) => {
    const bytes = await readFile(path.join('public', asset.renditionUrl.replace(/^\/+/u, '')));
    return {
      ...asset,
      contrastProfile: await assessImageContrastProfile(bytes),
    };
  }));
  await writeFile(MANIFEST_PATH, manifestSource({ ...current, assets }), 'utf8');
  process.stdout.write(`Refreshed ${assets.length} frozen stock contrast profiles.\n`);
}

void main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
  process.exitCode = 1;
});
