import { loadEnvConfig } from '@next/env';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { createClient } from '@supabase/supabase-js';
import {
  automaticStockBucket,
  automatedStockReview,
  deterministicStockAssetId,
  stockMood,
  stockOrientation,
} from '../src/lib/stock/curation';
import { fetchInteriorMaterialsCollection } from '../src/lib/stock/pexels-client';
import {
  STOCK_COLLECTION_ID,
  STOCK_MANIFEST_VERSION,
  type FrozenStockAsset,
  type FrozenStockManifest,
} from '../src/lib/stock/types';
import { assessImageContrastProfile } from '../src/lib/assets/image-contrast-profile';

loadEnvConfig(process.cwd());

const OUTPUT_DIR = path.join(process.cwd(), 'public/stock/pexels/interior-materials');
const MANIFEST_PATH = path.join(process.cwd(), 'src/lib/stock/workshop-manifest.generated.ts');
const SHOULD_REGISTER = process.argv.includes('--register');
const LICENSE_URL = 'https://www.pexels.com/license/' as const;

async function rendition(photo: Awaited<ReturnType<typeof fetchInteriorMaterialsCollection>>[number]) {
  const url = new URL(photo.src.original);
  url.searchParams.set('auto', 'compress');
  url.searchParams.set('cs', 'tinysrgb');
  url.searchParams.set('w', '1920');
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Pexels rendition ${photo.id} failed with ${response.status}`);
  const original = Buffer.from(await response.arrayBuffer());
  const encoded = await sharp(original)
    .rotate()
    .resize({ width: 1920, height: 1920, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 82, effort: 5 })
    .toBuffer({ resolveWithObject: true });
  const sourceRatio = photo.width / photo.height;
  const renditionRatio = encoded.info.width / encoded.info.height;
  if (Math.abs(sourceRatio - renditionRatio) > 0.02) {
    throw new Error(`Pexels dimension mismatch for ${photo.id}`);
  }
  return encoded;
}

async function registerAsset(asset: FrozenStockAsset): Promise<void> {
  if (!SHOULD_REGISTER) return;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!url || !key) throw new Error('Supabase service credentials are required with --register.');
  const supabase = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const storageKey = `stock/pexels/interior-materials/${asset.providerAssetId}.webp`;
  const insert = await supabase.from('asset_records').upsert({
    id: asset.assetId,
    client_id: null,
    site_id: null,
    origin: 'licensed_stock',
    media_type: 'image',
    storage_bucket: 'web-public',
    storage_key: storageKey,
    canonical_url: asset.renditionUrl,
    width: asset.width,
    height: asset.height,
    stock_key: asset.stockKey,
    provider: 'pexels',
    provider_asset_id: asset.providerAssetId,
    attribution: asset.attribution,
  }, { onConflict: 'stock_key', ignoreDuplicates: true });
  if (insert.error) throw new Error(`Stock registry failed: ${insert.error.message}`);
}

function manifestSource(manifest: FrozenStockManifest): string {
  return [
    "import type { FrozenStockManifest } from './types';",
    '',
    '/** Generated by scripts/sync-pexels-stock.ts; public rendering never calls Pexels. */',
    `export const WORKSHOP_STOCK_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const satisfies FrozenStockManifest;`,
    '',
  ].join('\n');
}

async function main() {
  const photos = await fetchInteriorMaterialsCollection();
  await mkdir(OUTPUT_DIR, { recursive: true });
  const assets: FrozenStockAsset[] = [];
  for (const photo of photos) {
    const stockKey = `stk.workshop.${photo.id}`;
    const review = automatedStockReview(photo);
    const output = await rendition(photo);
    const localPath = path.join(OUTPUT_DIR, `${photo.id}.webp`);
    await writeFile(localPath, output.data);
    const asset: FrozenStockAsset = {
      assetId: deterministicStockAssetId(stockKey),
      stockKey,
      providerAssetId: String(photo.id),
      collectionId: STOCK_COLLECTION_ID,
      bucket: automaticStockBucket(photo),
      orientation: stockOrientation(photo.width, photo.height),
      mood: stockMood(photo.avg_color),
      width: output.info.width,
      height: output.info.height,
      renditionUrl: `/stock/pexels/interior-materials/${photo.id}.webp`,
      contrastProfile: await assessImageContrastProfile(output.data),
      attribution: {
        provider: 'pexels',
        photographer: photo.photographer,
        photographerUrl: photo.photographer_url,
        sourceUrl: photo.url,
        licenseUrl: LICENSE_URL,
      },
      review: {
        algorithmVersion: 'pexels-curated-metadata-v1',
        passed: review.passed,
        reasons: review.reasons,
      },
    };
    assets.push(asset);
    await registerAsset(asset);
  }
  const manifest: FrozenStockManifest = {
    version: STOCK_MANIFEST_VERSION,
    collectionId: STOCK_COLLECTION_ID,
    syncedAt: new Date().toISOString(),
    assets,
  };
  await writeFile(MANIFEST_PATH, manifestSource(manifest));
  const eligible = assets.filter((asset) => asset.review.passed);
  process.stdout.write(JSON.stringify({
    collectionId: STOCK_COLLECTION_ID,
    sourceCount: assets.length,
    eligibleCount: eligible.length,
    rejectedCount: assets.length - eligible.length,
    landscapeCount: eligible.filter((asset) => asset.orientation.startsWith('landscape')).length,
    registered: SHOULD_REGISTER,
  }, null, 2) + '\n');
}

void main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
  process.exitCode = 1;
});
