import type { FrozenStockManifest } from './types';

/** Generated by scripts/sync-pexels-stock.ts; public rendering never calls Pexels. */
export const WORKSHOP_STOCK_MANIFEST = {
  "version": 1,
  "collectionId": "zmqu95c",
  "syncedAt": "2026-07-26T08:36:57.908Z",
  "assets": [
    {
      "assetId": "676bdaf6-8576-5f49-9951-702f188fa19b",
      "stockKey": "stk.workshop.5812",
      "providerAssetId": "5812",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/5812.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Karolina Grabowska www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g2",
        "sourceUrl": "https://www.pexels.com/photo/laminated-boards-5812/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#f0f6ff",
        "meanLuminance": 0.113599
      }
    },
    {
      "assetId": "3df07910-6a0b-5b15-8eb8-8e191a0c52df",
      "stockKey": "stk.workshop.276267",
      "providerAssetId": "276267",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1275,
      "renditionUrl": "/stock/pexels/interior-materials/276267.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Pixabay",
        "photographerUrl": "https://www.pexels.com/@pixabay",
        "sourceUrl": "https://www.pexels.com/photo/color-shade-samples-276267/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#010208",
        "brightestColor": "#f9fbff",
        "meanLuminance": 0.45408
      }
    },
    {
      "assetId": "20fc73d2-e841-5a3d-8b00-1febd9adae79",
      "stockKey": "stk.workshop.354939",
      "providerAssetId": "354939",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "dark",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/354939.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "隔壁光头老王 WangMing'Photo",
        "photographerUrl": "https://www.pexels.com/@wangming-photo-115695",
        "sourceUrl": "https://www.pexels.com/photo/assorted-paintings-on-green-wall-354939/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#0a120c",
        "brightestColor": "#fceaee",
        "meanLuminance": 0.082161
      }
    },
    {
      "assetId": "b94bd2b9-1389-58d5-869e-2c6a001c8998",
      "stockKey": "stk.workshop.941461",
      "providerAssetId": "941461",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/941461.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "saar bar yoseph",
        "photographerUrl": "https://www.pexels.com/@saar277",
        "sourceUrl": "https://www.pexels.com/photo/white-3d-wall-art-941461/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#262221",
        "brightestColor": "#e2e6f3",
        "meanLuminance": 0.235044
      }
    },
    {
      "assetId": "a0a2834a-623d-5941-aa37-0077bcc622da",
      "stockKey": "stk.workshop.4112799",
      "providerAssetId": "4112799",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "dark",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4112799.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Ariwan Sri Setya",
        "photographerUrl": "https://www.pexels.com/@ariwan-sri-setya-2493774",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-pink-textile-4112799/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#080000",
        "brightestColor": "#f3cad3",
        "meanLuminance": 0.074886
      }
    },
    {
      "assetId": "ee882f6f-e3af-5352-bbdc-f74cf89f7cbd",
      "stockKey": "stk.workshop.4249583",
      "providerAssetId": "4249583",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "light",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4249583.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edward Jenner",
        "photographerUrl": "https://www.pexels.com/@edward-jenner",
        "sourceUrl": "https://www.pexels.com/photo/white-and-brown-wall-mounted-frame-4249583/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#636a68",
        "brightestColor": "#f8f6f5",
        "meanLuminance": 0.526639
      }
    },
    {
      "assetId": "549cb045-a1ac-5844-904e-a2fa94b94fe2",
      "stockKey": "stk.workshop.4249592",
      "providerAssetId": "4249592",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "light",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/4249592.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edward Jenner",
        "photographerUrl": "https://www.pexels.com/@edward-jenner",
        "sourceUrl": "https://www.pexels.com/photo/white-printer-paper-on-wall-4249592/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#475641",
        "brightestColor": "#f2f5f1",
        "meanLuminance": 0.479044
      }
    },
    {
      "assetId": "141fbd29-ad71-55fa-956b-9ad8438b0cb7",
      "stockKey": "stk.workshop.4249687",
      "providerAssetId": "4249687",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "light",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4249687.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edward Jenner",
        "photographerUrl": "https://www.pexels.com/@edward-jenner",
        "sourceUrl": "https://www.pexels.com/photo/green-leaves-surrounded-by-marble-tiles-4249687/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#473225",
        "brightestColor": "#fcfdf8",
        "meanLuminance": 0.50144
      }
    },
    {
      "assetId": "453e41c3-bba0-54ae-9718-a89f3fc08a7b",
      "stockKey": "stk.workshop.4249689",
      "providerAssetId": "4249689",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "light",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4249689.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edward Jenner",
        "photographerUrl": "https://www.pexels.com/@edward-jenner",
        "sourceUrl": "https://www.pexels.com/photo/flat-lay-shot-of-marble-tiles-on-gray-surface-4249689/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#473227",
        "brightestColor": "#fcfdf7",
        "meanLuminance": 0.501894
      }
    },
    {
      "assetId": "7e217bd0-0a6c-5d21-8d79-95423ead0ee4",
      "stockKey": "stk.workshop.4250578",
      "providerAssetId": "4250578",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "light",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/4250578.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edward Jenner",
        "photographerUrl": "https://www.pexels.com/@edward-jenner",
        "sourceUrl": "https://www.pexels.com/photo/white-printer-paper-on-white-surface-4250578/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#656661",
        "brightestColor": "#f9f5f1",
        "meanLuminance": 0.71548
      }
    },
    {
      "assetId": "c32e71df-9e2d-5fb4-9f25-ff9f3afa86e4",
      "stockKey": "stk.workshop.4968690",
      "providerAssetId": "4968690",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "light",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4968690.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/paper-in-neutral-colors-fabric-and-other-craft-materials-4968690/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#060403",
        "brightestColor": "#e7ebee",
        "meanLuminance": 0.524834
      }
    },
    {
      "assetId": "868355ff-9c37-52e5-88ff-860507537810",
      "stockKey": "stk.workshop.4968694",
      "providerAssetId": "4968694",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "light",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/4968694.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-hand-working-with-fabric-samples-4968694/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": false,
        "reasons": [
          "person-or-body-metadata"
        ]
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#030306",
        "brightestColor": "#e8ecee",
        "meanLuminance": 0.54531
      }
    },
    {
      "assetId": "1920e464-5155-54ee-a1a2-c07e9991a4ff",
      "stockKey": "stk.workshop.4968717",
      "providerAssetId": "4968717",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "light",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/4968717.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/beige-and-grey-colour-samples-on-marble-table-4968717/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#706f69",
        "brightestColor": "#e2e6e9",
        "meanLuminance": 0.594238
      }
    },
    {
      "assetId": "4eaa842e-cfb6-5f1f-8bca-589b1b56e64f",
      "stockKey": "stk.workshop.4977402",
      "providerAssetId": "4977402",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/4977402.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "www.kaboompics.com",
        "photographerUrl": "https://www.pexels.com/@karola-g",
        "sourceUrl": "https://www.pexels.com/photo/people-holding-tile-samples-4977402/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": false,
        "reasons": [
          "person-or-body-metadata"
        ]
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#040502",
        "brightestColor": "#e8e8eb",
        "meanLuminance": 0.426651
      }
    },
    {
      "assetId": "468908be-bf42-5e3d-b0cd-74b4f460ac2d",
      "stockKey": "stk.workshop.5097279",
      "providerAssetId": "5097279",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/5097279.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/blue-egg-on-brown-wooden-chopping-board-5097279/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#020907",
        "brightestColor": "#ebf3f7",
        "meanLuminance": 0.275965
      }
    },
    {
      "assetId": "818da559-28f8-5cd8-bafd-1dbc71a606fc",
      "stockKey": "stk.workshop.6568675",
      "providerAssetId": "6568675",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6568675.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/black-and-white-stone-plates-in-hands-6568675/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": false,
        "reasons": [
          "person-or-body-metadata"
        ]
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#010100",
        "brightestColor": "#e0d4d4",
        "meanLuminance": 0.072681
      }
    },
    {
      "assetId": "1955c23c-9159-52f4-a59c-513dc99bd65e",
      "stockKey": "stk.workshop.6579992",
      "providerAssetId": "6579992",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6579992.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/interior-design-decorative-samples-6579992/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#010200",
        "brightestColor": "#f3f3f7",
        "meanLuminance": 0.377114
      }
    },
    {
      "assetId": "c1f511a4-10a7-5619-8d82-37cedaea1b1e",
      "stockKey": "stk.workshop.6580005",
      "providerAssetId": "6580005",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6580005.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/two-people-touching-fabric-samples-6580005/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": false,
        "reasons": [
          "person-or-body-metadata"
        ]
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#030401",
        "brightestColor": "#f1f1f3",
        "meanLuminance": 0.36175
      }
    },
    {
      "assetId": "41a49b9d-8ec9-51c2-9d21-0b57c6423acb",
      "stockKey": "stk.workshop.6580007",
      "providerAssetId": "6580007",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6580007.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/interior-design-decorative-samples-6580007/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#020200",
        "brightestColor": "#ffffff",
        "meanLuminance": 0.369373
      }
    },
    {
      "assetId": "5af505ae-b0b7-520c-a9b5-3e23c1ff89c0",
      "stockKey": "stk.workshop.6580567",
      "providerAssetId": "6580567",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6580567.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/people-looking-at-different-fabrics-6580567/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": false,
        "reasons": [
          "person-or-body-metadata"
        ]
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000100",
        "brightestColor": "#f1f1f5",
        "meanLuminance": 0.393935
      }
    },
    {
      "assetId": "99d73324-0712-57a7-9f53-646800b9cdcb",
      "stockKey": "stk.workshop.6648440",
      "providerAssetId": "6648440",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/6648440.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-leather-catalog-color-palette-6648440/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#020902",
        "brightestColor": "#f3f5f9",
        "meanLuminance": 0.342095
      }
    },
    {
      "assetId": "ae178026-f804-5d6d-897b-9e491ffdc24d",
      "stockKey": "stk.workshop.6952650",
      "providerAssetId": "6952650",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "light",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/6952650.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Eva Bronzini",
        "photographerUrl": "https://www.pexels.com/@eva-bronzini",
        "sourceUrl": "https://www.pexels.com/photo/close-up-shot-of-a-marble-6952650/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#654920",
        "brightestColor": "#f7efe3",
        "meanLuminance": 0.468772
      }
    },
    {
      "assetId": "d8cdaa6f-b492-5b12-ad4d-91ebed4eee72",
      "stockKey": "stk.workshop.7232508",
      "providerAssetId": "7232508",
      "collectionId": "zmqu95c",
      "bucket": "HP",
      "orientation": "landscape-wide",
      "mood": "balanced",
      "width": 1920,
      "height": 1080,
      "renditionUrl": "/stock/pexels/interior-materials/7232508.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Artem Podrez",
        "photographerUrl": "https://www.pexels.com/@artempodrez",
        "sourceUrl": "https://www.pexels.com/photo/rough-concrete-surface-7232508/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#3b2f0a",
        "brightestColor": "#eae3db",
        "meanLuminance": 0.343683
      }
    },
    {
      "assetId": "2c5a5775-10c1-56cf-b916-46d9c8a6f3e6",
      "stockKey": "stk.workshop.7504598",
      "providerAssetId": "7504598",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/7504598.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "cottonbro studio",
        "photographerUrl": "https://www.pexels.com/@cottonbro",
        "sourceUrl": "https://www.pexels.com/photo/wood-tiles-on-the-table-7504598/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000406",
        "brightestColor": "#e4e2df",
        "meanLuminance": 0.369728
      }
    },
    {
      "assetId": "fc0bc2cc-0ec6-56d9-a441-ade357a5745a",
      "stockKey": "stk.workshop.7828176",
      "providerAssetId": "7828176",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/7828176.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Mikhail Nilov",
        "photographerUrl": "https://www.pexels.com/@mikhail-nilov",
        "sourceUrl": "https://www.pexels.com/photo/square-tiles-on-purple-surface-7828176/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#0b070b",
        "brightestColor": "#b786b2",
        "meanLuminance": 0.189309
      }
    },
    {
      "assetId": "db9e496e-44f6-52b1-8a4c-fa3d27eb68ae",
      "stockKey": "stk.workshop.7828306",
      "providerAssetId": "7828306",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/7828306.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Mikhail Nilov",
        "photographerUrl": "https://www.pexels.com/@mikhail-nilov",
        "sourceUrl": "https://www.pexels.com/photo/blue-sphere-object-between-blocks-7828306/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000706",
        "brightestColor": "#ddc2d8",
        "meanLuminance": 0.376865
      }
    },
    {
      "assetId": "1a474a4d-6982-52ef-880a-9ceca8798bae",
      "stockKey": "stk.workshop.7828541",
      "providerAssetId": "7828541",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/7828541.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Mikhail Nilov",
        "photographerUrl": "https://www.pexels.com/@mikhail-nilov",
        "sourceUrl": "https://www.pexels.com/photo/black-and-white-wall-decor-7828541/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000500",
        "brightestColor": "#c7c1be",
        "meanLuminance": 0.212114
      }
    },
    {
      "assetId": "71fe5988-98dc-504a-8f77-f077f6a66d1b",
      "stockKey": "stk.workshop.8122356",
      "providerAssetId": "8122356",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1539,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/8122356.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Namukolo Siyumbwa",
        "photographerUrl": "https://www.pexels.com/@namukolo-siyumbwa-62572692",
        "sourceUrl": "https://www.pexels.com/photo/beautiful-wall-tiles-8122356/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#131412",
        "brightestColor": "#aba5a8",
        "meanLuminance": 0.060291
      }
    },
    {
      "assetId": "ce7d5726-0f2c-520a-ac41-9bb322cd8f66",
      "stockKey": "stk.workshop.9219511",
      "providerAssetId": "9219511",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1440,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/9219511.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Sveta K",
        "photographerUrl": "https://www.pexels.com/@sveta-k-75705601",
        "sourceUrl": "https://www.pexels.com/photo/wooden-floor-with-shadows-9219511/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#2c2920",
        "brightestColor": "#c2b0ab",
        "meanLuminance": 0.099825
      }
    },
    {
      "assetId": "c62db2cb-0b69-5362-8fc0-8d8b3eec1a26",
      "stockKey": "stk.workshop.10780943",
      "providerAssetId": "10780943",
      "collectionId": "zmqu95c",
      "bucket": "HP",
      "orientation": "landscape-wide",
      "mood": "balanced",
      "width": 1920,
      "height": 1080,
      "renditionUrl": "/stock/pexels/interior-materials/10780943.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Yusuf P",
        "photographerUrl": "https://www.pexels.com/@artyusufpatel",
        "sourceUrl": "https://www.pexels.com/photo/wooden-chair-in-an-empty-room-in-sunlight-10780943/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#120801",
        "brightestColor": "#fffbd9",
        "meanLuminance": 0.30957
      }
    },
    {
      "assetId": "5719512d-8f1b-56c8-b39a-25babf583047",
      "stockKey": "stk.workshop.12040694",
      "providerAssetId": "12040694",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/12040694.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Mathias Reding",
        "photographerUrl": "https://www.pexels.com/@matreding",
        "sourceUrl": "https://www.pexels.com/photo/photo-of-a-door-reflected-in-a-mirror-in-a-modern-interior-12040694/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000f00",
        "brightestColor": "#cdcbd9",
        "meanLuminance": 0.299299
      }
    },
    {
      "assetId": "57c342de-a9d7-5f46-b577-dbc79a427277",
      "stockKey": "stk.workshop.15156178",
      "providerAssetId": "15156178",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/15156178.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Magda Ehlers",
        "photographerUrl": "https://www.pexels.com/@magda-ehlers-pexels",
        "sourceUrl": "https://www.pexels.com/photo/marble-tiles-formign-star-shaped-pattern-15156178/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#292929",
        "brightestColor": "#ffffff",
        "meanLuminance": 0.430563
      }
    },
    {
      "assetId": "f231798e-3cc9-5678-a1e3-7e8ad245007a",
      "stockKey": "stk.workshop.15273824",
      "providerAssetId": "15273824",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/15273824.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Magda Ehlers",
        "photographerUrl": "https://www.pexels.com/@magda-ehlers-pexels",
        "sourceUrl": "https://www.pexels.com/photo/marble-tiles-on-floor-indoors-15273824/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000001",
        "brightestColor": "#dbd5c5",
        "meanLuminance": 0.158207
      }
    },
    {
      "assetId": "f31d52b4-2006-52ad-8846-fdb43ee237e8",
      "stockKey": "stk.workshop.16202240",
      "providerAssetId": "16202240",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1536,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/16202240.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Tuherdias Awang",
        "photographerUrl": "https://www.pexels.com/@tuherdias-awang-20922123",
        "sourceUrl": "https://www.pexels.com/photo/tiles-on-floor-16202240/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#050604",
        "brightestColor": "#fbf9f8",
        "meanLuminance": 0.391889
      }
    },
    {
      "assetId": "cad8f49b-9c63-54e8-85d1-8fdc2f617370",
      "stockKey": "stk.workshop.16790953",
      "providerAssetId": "16790953",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1439,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/16790953.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Ilham Ahnaf",
        "photographerUrl": "https://www.pexels.com/@ilham-ahnaf-2828359",
        "sourceUrl": "https://www.pexels.com/photo/lamps-and-floor-in-empty-room-16790953/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#110b0e",
        "brightestColor": "#e5e8e1",
        "meanLuminance": 0.297734
      }
    },
    {
      "assetId": "aba3ce06-3db0-5e4f-ab69-1a9b4896e2b8",
      "stockKey": "stk.workshop.18620044",
      "providerAssetId": "18620044",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/18620044.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "aboodi vesakaran",
        "photographerUrl": "https://www.pexels.com/@aboodi",
        "sourceUrl": "https://www.pexels.com/photo/wooden-wall-over-railing-18620044/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#ffffff",
        "meanLuminance": 0.247272
      }
    },
    {
      "assetId": "5bbcc09a-e2b5-5021-8103-434faa62bce7",
      "stockKey": "stk.workshop.19328891",
      "providerAssetId": "19328891",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1440,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/19328891.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "tiago alves",
        "photographerUrl": "https://www.pexels.com/@tiago-alves-710726839",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-fabric-samples-lying-on-a-desk-19328891/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#0e0802",
        "brightestColor": "#d9dce4",
        "meanLuminance": 0.285501
      }
    },
    {
      "assetId": "5bf7a966-a814-578c-b258-c88f9237a895",
      "stockKey": "stk.workshop.22982113",
      "providerAssetId": "22982113",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/22982113.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Jan van der Wolf",
        "photographerUrl": "https://www.pexels.com/@jan-van-der-wolf-11680885",
        "sourceUrl": "https://www.pexels.com/photo/view-of-a-modern-ceiling-22982113/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#060908",
        "brightestColor": "#ffffff",
        "meanLuminance": 0.159696
      }
    },
    {
      "assetId": "7aa128d9-49c7-5c68-a11e-b34c11460b32",
      "stockKey": "stk.workshop.28180778",
      "providerAssetId": "28180778",
      "collectionId": "zmqu95c",
      "bucket": "HL",
      "orientation": "landscape-wide",
      "mood": "dark",
      "width": 1920,
      "height": 1222,
      "renditionUrl": "/stock/pexels/interior-materials/28180778.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Michael Manulevich",
        "photographerUrl": "https://www.pexels.com/@michael-manulevich-759274198",
        "sourceUrl": "https://www.pexels.com/photo/a-close-up-of-a-wooden-panel-with-a-pattern-28180778/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#1c0e00",
        "brightestColor": "#ffcb9a",
        "meanLuminance": 0.076025
      }
    },
    {
      "assetId": "bcc32016-ecb0-5ecb-b8fe-4d05c125f63a",
      "stockKey": "stk.workshop.30112372",
      "providerAssetId": "30112372",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/30112372.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Deane Bayas",
        "photographerUrl": "https://www.pexels.com/@dbaler",
        "sourceUrl": "https://www.pexels.com/photo/granite-and-stone-slabs-in-factory-setting-30112372/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#010200",
        "brightestColor": "#fefaff",
        "meanLuminance": 0.457362
      }
    },
    {
      "assetId": "0fbc7d80-81a7-5bb7-b097-28ce24301003",
      "stockKey": "stk.workshop.33425500",
      "providerAssetId": "33425500",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1080,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/33425500.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Edgar Martínez",
        "photographerUrl": "https://www.pexels.com/@edgar-martinez-2154660358",
        "sourceUrl": "https://www.pexels.com/photo/stack-of-colorful-synthetic-leather-fabrics-33425500/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#ceb195",
        "meanLuminance": 0.070065
      }
    },
    {
      "assetId": "f7df7bb8-63ca-5d3e-9a2a-f56324411f03",
      "stockKey": "stk.workshop.33685861",
      "providerAssetId": "33685861",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1267,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/33685861.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Essentia Media",
        "photographerUrl": "https://www.pexels.com/@essentia-media-2154502099",
        "sourceUrl": "https://www.pexels.com/photo/modern-minimalist-interior-with-marble-and-wood-33685861/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#010101",
        "brightestColor": "#d3dbe5",
        "meanLuminance": 0.199426
      }
    },
    {
      "assetId": "96ee3b55-10a9-5f62-b5bd-5057365a4a1e",
      "stockKey": "stk.workshop.33685863",
      "providerAssetId": "33685863",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/33685863.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Essentia Media",
        "photographerUrl": "https://www.pexels.com/@essentia-media-2154502099",
        "sourceUrl": "https://www.pexels.com/photo/elegant-modern-interior-with-marble-facade-33685863/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#090802",
        "brightestColor": "#caced2",
        "meanLuminance": 0.184214
      }
    },
    {
      "assetId": "230f5a57-1fef-5fc6-bd01-5b80fe146bb5",
      "stockKey": "stk.workshop.36077584",
      "providerAssetId": "36077584",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "dark",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/36077584.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "HUUM  │sauna heaters",
        "photographerUrl": "https://www.pexels.com/@huum-sauna-heaters-718199222",
        "sourceUrl": "https://www.pexels.com/photo/modern-sauna-interior-with-wood-panels-36077584/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#fcd5a6",
        "meanLuminance": 0.094927
      }
    },
    {
      "assetId": "01a9f6a1-6268-5eb2-8e10-9327bb3e5733",
      "stockKey": "stk.workshop.36162732",
      "providerAssetId": "36162732",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1371,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/36162732.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Peter Dyllong",
        "photographerUrl": "https://www.pexels.com/@peter-dyllong-2158803154",
        "sourceUrl": "https://www.pexels.com/photo/concrete-construction-site-with-building-materials-36162732/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#e4d2c7",
        "meanLuminance": 0.333721
      }
    },
    {
      "assetId": "e79bc7e3-4a34-579a-8340-4543456840f4",
      "stockKey": "stk.workshop.36214622",
      "providerAssetId": "36214622",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "balanced",
      "width": 1201,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/36214622.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Babajide Olusanya",
        "photographerUrl": "https://www.pexels.com/@babajide-olusanya-2151643024",
        "sourceUrl": "https://www.pexels.com/photo/stack-of-decorative-textured-fabric-rolls-36214622/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#110e0a",
        "brightestColor": "#eaecef",
        "meanLuminance": 0.216826
      }
    },
    {
      "assetId": "6554e71d-a029-5204-8625-de9b01b268b6",
      "stockKey": "stk.workshop.36299688",
      "providerAssetId": "36299688",
      "collectionId": "zmqu95c",
      "bucket": "MP",
      "orientation": "portrait",
      "mood": "dark",
      "width": 1280,
      "height": 1920,
      "renditionUrl": "/stock/pexels/interior-materials/36299688.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Jonathan Borba",
        "photographerUrl": "https://www.pexels.com/@jonathanborba",
        "sourceUrl": "https://www.pexels.com/photo/natural-wood-texture-with-unique-grain-patterns-36299688/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#050c0d",
        "brightestColor": "#eec4af",
        "meanLuminance": 0.136245
      }
    },
    {
      "assetId": "1dda5384-c463-53c0-86d4-e2ba4825f59c",
      "stockKey": "stk.workshop.38277107",
      "providerAssetId": "38277107",
      "collectionId": "zmqu95c",
      "bucket": "HL",
      "orientation": "landscape-wide",
      "mood": "dark",
      "width": 1920,
      "height": 1186,
      "renditionUrl": "/stock/pexels/interior-materials/38277107.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Rohit Bhusan",
        "photographerUrl": "https://www.pexels.com/@rohitbhusan",
        "sourceUrl": "https://www.pexels.com/photo/close-up-of-abstract-wooden-texture-with-geometric-patterns-38277107/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#000000",
        "brightestColor": "#988e91",
        "meanLuminance": 0.043385
      }
    },
    {
      "assetId": "167538bf-6878-5ca9-a346-508514894963",
      "stockKey": "stk.workshop.38348269",
      "providerAssetId": "38348269",
      "collectionId": "zmqu95c",
      "bucket": "ML",
      "orientation": "landscape-card",
      "mood": "balanced",
      "width": 1920,
      "height": 1280,
      "renditionUrl": "/stock/pexels/interior-materials/38348269.webp",
      "attribution": {
        "provider": "pexels",
        "photographer": "Bezalens JGP",
        "photographerUrl": "https://www.pexels.com/@bezalens",
        "sourceUrl": "https://www.pexels.com/photo/abstract-wooden-texture-with-geometric-pattern-38348269/",
        "licenseUrl": "https://www.pexels.com/license/"
      },
      "review": {
        "algorithmVersion": "pexels-curated-metadata-v1",
        "passed": true,
        "reasons": []
      },
      "contrastProfile": {
        "algorithmVersion": "image-channel-range-v1",
        "darkestColor": "#2f0100",
        "brightestColor": "#ffffce",
        "meanLuminance": 0.190313
      }
    }
  ]
} as const satisfies FrozenStockManifest;
